import type { RugSpec } from "@/lib/types";

export const herizDefaults: Partial<RugSpec> = {
  style: "heriz",
  symmetry: "mirror-both",
  variation: 0.12,
  palette: {
    background: "c0",
    colors: [
      { id: "c0", name: "Brick Red",     hex: "#9B3A2A" },
      { id: "c1", name: "Deep Indigo",   hex: "#1F2D5C" },
      { id: "c2", name: "Cream",         hex: "#EDE8D5" },
      { id: "c3", name: "Burnt Orange",  hex: "#C4611A" },
      { id: "c4", name: "Sage Green",    hex: "#5A7A45" },
      { id: "c5", name: "Ochre",         hex: "#C9A020" },
      { id: "c6", name: "Pale Blue",     hex: "#7AAAC0" },
      { id: "c7", name: "Charcoal",      hex: "#3A3A3A" },
    ],
  },
  layout: {
    border: {
      mainBorderWidth: 0.1,
      guardWidth: 0.025,
      tileRepeatX: 6,
      motif: "geometric",
      color: "c1",
      accentColor: "c3",
    },
    medallion: {
      enabled: true,
      sizeX: 0.45,
      sizeY: 0.35,
      complexity: 0.6,
      color: "c1",
      accentColor: "c5",
      innerRings: 1,
    },
    field: {
      vineEnabled: false,
      vineDensity: 0,
      vineCurvature: 0,
      vineColor: "c4",
      leavesEnabled: false,
      leafSize: 0,
      leafRoundness: 0.3,
      leafColor: "c4",
      flowersEnabled: true,
      flowerSize: 0.6,
      flowerComplexity: 0.5,
      flowerColor: "c2",
      flowerAccentColor: "c5",
      palmettesEnabled: true,
      palmetteSize: 0.65,
      palmetteColor: "c3",
      heratiEnabled: false,
      heratiDensity: 0,
    },
  },
};
