import type { RugSpec } from "@/lib/types";

export const kashanDefaults: Partial<RugSpec> = {
  style: "kashan",
  symmetry: "mirror-both",
  variation: 0.05,
  palette: {
    background: "c0",
    colors: [
      { id: "c0", name: "Royal Burgundy",  hex: "#5C0A2E" },
      { id: "c1", name: "Deep Blue",       hex: "#14264A" },
      { id: "c2", name: "Antique White",   hex: "#F5EFE0" },
      { id: "c3", name: "Emerald",         hex: "#1A5C35" },
      { id: "c4", name: "Pale Gold",       hex: "#D4AF57" },
      { id: "c5", name: "Blush Pink",      hex: "#D4899A" },
      { id: "c6", name: "Turquoise",       hex: "#3A8A8A" },
      { id: "c7", name: "Warm Brown",      hex: "#7A4A2A" },
    ],
  },
  layout: {
    border: {
      mainBorderWidth: 0.14,
      guardWidth: 0.035,
      tileRepeatX: 10,
      motif: "floral-stripe",
      color: "c1",
      accentColor: "c4",
    },
    medallion: {
      enabled: true,
      sizeX: 0.35,
      sizeY: 0.26,
      complexity: 0.9,
      color: "c1",
      accentColor: "c4",
      innerRings: 3,
    },
    field: {
      vineEnabled: true,
      vineDensity: 0.55,
      vineCurvature: 0.85,
      vineColor: "c3",
      leavesEnabled: true,
      leafSize: 0.4,
      leafRoundness: 0.75,
      leafColor: "c3",
      flowersEnabled: true,
      flowerSize: 0.5,
      flowerComplexity: 0.9,
      flowerColor: "c5",
      flowerAccentColor: "c4",
      palmettesEnabled: true,
      palmetteSize: 0.45,
      palmetteColor: "c2",
      heratiEnabled: false,
      heratiDensity: 0,
    },
  },
};
