import type { RugSpec } from "@/lib/types";

export const saroukDefaults: Partial<RugSpec> = {
  style: "sarouk",
  symmetry: "mirror-both",
  variation: 0.08,
  palette: {
    background: "c0",
    colors: [
      { id: "c0", name: "Deep Crimson", hex: "#7B1B1B" },
      { id: "c1", name: "Midnight Navy", hex: "#1A2644" },
      { id: "c2", name: "Antique Ivory", hex: "#F2ECD8" },
      { id: "c3", name: "Forest Green", hex: "#2D5016" },
      { id: "c4", name: "Warm Gold", hex: "#C9A84C" },
      { id: "c5", name: "Dusty Rose", hex: "#C47B7B" },
      { id: "c6", name: "Cobalt Blue", hex: "#2B4F8C" },
      { id: "c7", name: "Terracotta", hex: "#B5541A" },
    ],
  },
  layout: {
    border: {
      mainBorderWidth: 0.12,
      guardWidth: 0.03,
      tileRepeatX: 8,
      motif: "vine-scroll",
      color: "c1",
      accentColor: "c2",
    },
    medallion: {
      enabled: true,
      sizeX: 0.38,
      sizeY: 0.28,
      complexity: 0.75,
      color: "c1",
      accentColor: "c4",
      innerRings: 2,
    },
    field: {
      vineEnabled: true,
      vineDensity: 0.65,
      vineCurvature: 0.8,
      vineColor: "c3",
      leavesEnabled: true,
      leafSize: 0.45,
      leafRoundness: 0.7,
      leafColor: "c3",
      flowersEnabled: true,
      flowerSize: 0.55,
      flowerComplexity: 0.8,
      flowerColor: "c5",
      flowerAccentColor: "c4",
      palmettesEnabled: true,
      palmetteSize: 0.5,
      palmetteColor: "c2",
      heratiEnabled: false,
      heratiDensity: 0,
    },
  },
};
