import type { RugSpec } from "@/lib/types";

export const tabrizDefaults: Partial<RugSpec> = {
  style: "tabriz",
  symmetry: "mirror-both",
  variation: 0.07,
  palette: {
    background: "c0",
    colors: [
      { id: "c0", name: "Warm Camel",    hex: "#8B6914" },
      { id: "c1", name: "Deep Red",      hex: "#6B1515" },
      { id: "c2", name: "Ivory",         hex: "#F0EAD6" },
      { id: "c3", name: "Navy",          hex: "#1A2444" },
      { id: "c4", name: "Olive Green",   hex: "#4A5C2A" },
      { id: "c5", name: "Apricot",       hex: "#D4815A" },
      { id: "c6", name: "Steel Blue",    hex: "#4A6A8A" },
      { id: "c7", name: "Gold",          hex: "#C9A030" },
    ],
  },
  layout: {
    border: {
      mainBorderWidth: 0.11,
      guardWidth: 0.028,
      tileRepeatX: 9,
      motif: "floral-stripe",
      color: "c1",
      accentColor: "c2",
    },
    medallion: {
      enabled: true,
      sizeX: 0.4,
      sizeY: 0.3,
      complexity: 0.8,
      color: "c3",
      accentColor: "c7",
      innerRings: 2,
    },
    field: {
      vineEnabled: true,
      vineDensity: 0.5,
      vineCurvature: 0.7,
      vineColor: "c4",
      leavesEnabled: true,
      leafSize: 0.42,
      leafRoundness: 0.65,
      leafColor: "c4",
      flowersEnabled: true,
      flowerSize: 0.52,
      flowerComplexity: 0.75,
      flowerColor: "c5",
      flowerAccentColor: "c7",
      palmettesEnabled: true,
      palmetteSize: 0.48,
      palmetteColor: "c2",
      heratiEnabled: false,
      heratiDensity: 0,
    },
  },
};
